### ISSUE TITLE
minor features

### ISSUE THREAD

**Issue by kobi2187** [ciscoheat/buddy#50]
Hi, 
- please add some color to the terminal reporter.
- please allow comparing arrays with should.be (right now, it is by reference only)
    - it is usable with array.should.containExactly

**Comment by ciscoheat** [comment]
Hi, thanks for your feedback! 

Coloring is a good idea, the problem is that you either need another reporter for that, or a platform-consistent TTY detection (and I'm jumping through quite a few hoops already with asynchronous delays and `main()` code generation.) But it's a good idea that I'll consider.

Array comparison with `should.be` is by reference (identity) as [stated in the docs](https://github.com/ciscoheat/buddy#all-types), I even added a [special python section](https://github.com/ciscoheat/buddy/blob/master/src/buddy/Should.hx#L471-L476) to ensure that. 

For item-by-item checks in an array, you can use `containExactly` as you say, or the other iterable methods: https://github.com/ciscoheat/buddy#iterable

**Comment by kobi2187** [comment]
okay, thank you.
the library is very nice, and does all i need (for now).
coloring is just easier to see. perhaps i will implement the reporter interface, like the docs say.
I've made snippets for vscode. it greatly simplifies the workflow for me.

**Comment by ciscoheat** [comment]
Glad you like it. :) Have you created snippets for buddy suites and specs? I'm happy to add a link to them if they are public somewhere.

**Comment by ciscoheat** [comment]
I'll add a ConsoleColorReporter and options for enabling colors in the next release, it shouldn't be too long.

**Comment by kobi2187** [comment]
cool, thank you!
I made snippets though I don't really know the philosophy and terminology of BDD, so I made the wording fit my line of thinking. you can change that if you want to include it.
I can email it to you, making a repo just for that seems exaggerated.
my email address is kobi2187@gmail.com send me a note and i'll reply :-)
